# @package _global_
# problem args

DSET: "sgbs_merged_unf_val8_seed123_"

model_args:
  problem: "cvrp"
  graph_size: 500
  train_dataset: data/scoring_data/train_nrr_data_sgbs_merged_unf_val8_seed123.npz
  val_dataset: data/scoring_data/val_nrr_data_sgbs_merged_unf_val8_seed123.npz
