# @package _global_
# problem args

DSET: ""
problem: "cvrp"
graph_size: 1000
train_dataset: #
val_dataset: #
test_dataset: data/CVRP/benchmark/uchoa/n3.dat
n_seeds: 3
nrr_time_limit: 120
nrr_max_iters: 10000
dataset_size: #
