# @package _global_
# primary nsf_config file for experiments

defaults:
  - _self_
  - problem: cvrp500_mixed
  - method: score_savings_knn_all
  - solver: lkh
  - meta: score
  - override hydra/job_logging: simple


hydra:
  # standard output path
  # change with command line argument: hydra.run.dir=XXX
  run:
    dir: outputs/scoring_data/${DSET}${problem}_${graph_size}/${nrr_cfg.init_method}_${nrr_cfg.sg_construction_method}_${nrr_cfg.accept_method}/${now:%Y-%m-%d_%H-%M-%S_%f}

  output_subdir: _scoring_data_log

  # overwrite root log level
  job_logging:
    root:
      level: ${log_lvl}

  #
  # help flag output. customize for application
  help:
    # App name, override to match the name your app is known by
    app_name: ${hydra.job.name}.py - train or evaluate specified models according to nsf_config.

    # Help header, customize to describe your app to your users
    header: |
      ${hydra.help.app_name}

    footer: |
      Use --hydra-help to view Hydra specific help

    template: |
      ${hydra.help.header}
      == Configuration groups ==
      Compose your configuration from those groups (group=option)

      $APP_CONFIG_GROUPS

      == Config ==
      Override anything in the config (foo.bar=value)

      $CONFIG

      ${hydra.help.footer}
