# @package _global_
# model parameters

nrr_cfg:
  init_method: 'savings'
  init_method_cfg:
    savings_function: 'clarke_wright'
  sg_construction_method: 'tour_knn'
  sg_construction_method_cfg:
    knn: 8   # L2D paper: 10
  scoring_method: 'rnd'
  scoring_method_cfg: #
  sg_selection_method: 'multi'
  sg_selection_method_cfg: #
  accept_method: 'all'
  accept_method_cfg: #
