# @package _global_

debug_lvl: 1  # 0 disables debugging and verbosity completely, >1 activates additional debugging functionality
log_lvl: INFO
global_seed: 1234

n_seeds: 2
nrr_time_limit: 30
nrr_max_iters: 100
dataset: ${val_dataset}
dataset_size: 3
