# @package _global_

debug_lvl: 0  # 0 disables debugging and verbosity completely, >1 activates additional debugging functionality
log_lvl: INFO   # ERROR
global_seed: 1234

n_seeds: 3
dataset: ${test_dataset}
dataset_size: 32
